# Generated by Django 2.2.12 on 2021-05-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publisher',
            table=None,
        ),
    ]
